-- Auth provider accounts and professional fields migration
-- Generated by assistant: adds ProviderAccount table and extends users with phone/name/professionalType

-- 1) Enum for professional types
DO $$ BEGIN
  CREATE TYPE "ProfessionalType" AS ENUM ('AGENT','LANDLORD','LENDER','CONTRACTOR');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 2) Extend users table
ALTER TABLE "users"
  ALTER COLUMN "email" DROP NOT NULL;

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "phone" TEXT,
  ADD COLUMN IF NOT EXISTS "firstName" TEXT,
  ADD COLUMN IF NOT EXISTS "lastName" TEXT,
  ADD COLUMN IF NOT EXISTS "professionalType" "ProfessionalType";

-- Unique on phone (Postgres allows multiple NULLs)
DO $$ BEGIN
  ALTER TABLE "users" ADD CONSTRAINT "users_phone_key" UNIQUE ("phone");
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- 3) Provider accounts table
CREATE TABLE IF NOT EXISTS "provider_accounts" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "email" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "provider_accounts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "provider_accounts_user_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Unique and indexes
DO $$ BEGIN
  CREATE UNIQUE INDEX "provider_accounts_provider_providerId_key" ON "provider_accounts" ("provider", "providerId");
EXCEPTION
  WHEN duplicate_table THEN null;
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE INDEX "provider_accounts_email_idx" ON "provider_accounts" ("email");
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;


