import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

@Injectable()
export class OpenAIService {
  private readonly logger = new Logger(OpenAIService.name);
  private readonly apiKey: string;
  private readonly baseUrl: string;

  constructor(private readonly configService: ConfigService) {
    this.apiKey = this.configService.get<string>('OPENAI_API_KEY') || '';
    this.baseUrl = this.configService.get<string>('OPENAI_BASE_URL') || 'https://api.openai.com/v1';
  }

  async generateText(prompt: string, maxTokens: number = 1000): Promise<string> {
    try {
      if (!this.apiKey) {
        this.logger.warn('OpenAI API key not configured, returning mock response');
        return this.generateMockResponse(prompt);
      }

      // Mock implementation - replace with actual OpenAI API call
      this.logger.log(`Generating text with prompt: ${prompt.substring(0, 100)}...`);
      return this.generateMockResponse(prompt);
    } catch (error) {
      this.logger.error('Error generating text with OpenAI:', error);
      return this.generateMockResponse(prompt);
    }
  }

  async generateReportContent(template: string, data: Record<string, any>): Promise<string> {
    try {
      const prompt = this.buildReportPrompt(template, data);
      return await this.generateText(prompt, 2000);
    } catch (error) {
      this.logger.error('Error generating report content:', error);
      return this.generateMockReportContent(template, data);
    }
  }

  async analyzePropertyData(propertyData: Record<string, any>): Promise<string> {
    try {
      const prompt = this.buildAnalysisPrompt(propertyData);
      return await this.generateText(prompt, 1500);
    } catch (error) {
      this.logger.error('Error analyzing property data:', error);
      return this.generateMockAnalysis(propertyData);
    }
  }

  async generateInsights(data: Record<string, any>): Promise<string> {
    try {
      const prompt = this.buildInsightsPrompt(data);
      return await this.generateText(prompt, 1000);
    } catch (error) {
      this.logger.error('Error generating insights:', error);
      return this.generateMockInsights(data);
    }
  }

  // Added helpers expected by ReportBuilderService
  async generatePropertySummary(property: any, propertyData: any): Promise<string> {
    const prompt = `Write a concise executive summary (3-5 sentences) for the property at ${property?.address || 'Unknown'}, ${property?.city || ''} ${property?.state || ''}. Use the following context when helpful:\n\n${JSON.stringify(propertyData || {}, null, 2)}`;
    return this.generateText(prompt, 800);
  }

  async generateInsightsForReport(property: any, propertyData: any, incidents: any, insurance: any): Promise<any> {
    const prompt = `Provide JSON insights for a property report. Return ONLY valid JSON with the shape {"recommendations": string[]}.\n\nProperty: ${JSON.stringify(property || {}, null, 2)}\n\nData: ${JSON.stringify(propertyData || {}, null, 2)}\n\nIncidents: ${JSON.stringify(incidents || {}, null, 2)}\n\nInsurance: ${JSON.stringify(insurance || {}, null, 2)}`;
    const text = await this.generateText(prompt, 1000);
    try {
      const parsed = JSON.parse(text);
      return parsed;
    } catch (e) {
      return { recommendations: [text] };
    }
  }

  private buildReportPrompt(template: string, data: Record<string, any>): string {
    return `Generate a professional real estate report based on the following template and data:

Template: ${template}

Property Data: ${JSON.stringify(data, null, 2)}

Please generate a comprehensive, well-structured report that includes all relevant information from the data provided.`;
  }

  private buildAnalysisPrompt(propertyData: Record<string, any>): string {
    return `Analyze the following property data and provide insights:

Property Data: ${JSON.stringify(propertyData, null, 2)}

Please provide:
1. Key observations about the property
2. Potential concerns or highlights
3. Market positioning analysis
4. Recommendations for buyers/sellers`;
  }

  private buildInsightsPrompt(data: Record<string, any>): string {
    return `Based on the following data, provide key insights and observations:

Data: ${JSON.stringify(data, null, 2)}

Please provide actionable insights and recommendations.`;
  }

  private generateMockResponse(prompt: string): string {
    return `This is a mock response to: "${prompt.substring(0, 100)}...". In a production environment, this would be generated by OpenAI's API.`;
  }

  private generateMockReportContent(template: string, data: Record<string, any>): string {
    return `# Property Report

## Executive Summary
This is a mock report generated for demonstration purposes.

## Property Details
- Address: ${data.address || 'N/A'}
- Type: ${data.propertyType || 'N/A'}
- Year Built: ${data.yearBuilt || 'N/A'}

## Analysis
This mock report provides a template structure that would be populated with real AI-generated content in production.

## Recommendations
Consider this a placeholder for AI-generated insights and recommendations.`;
  }

  private generateMockAnalysis(propertyData: Record<string, any>): string {
    return `## Property Analysis

This is a mock analysis of the property data. In production, this would contain AI-generated insights based on:

- Property characteristics
- Market data
- Comparable properties
- Risk factors

The analysis would provide actionable insights for decision-making.`;
  }

  private generateMockInsights(data: Record<string, any>): string {
    return `## Key Insights

This is a mock insights section. In production, AI would analyze the data to provide:

1. **Market Trends**: Analysis of current market conditions
2. **Property Strengths**: Key advantages of this property
3. **Areas of Concern**: Potential issues to consider
4. **Recommendations**: Actionable next steps

These insights would be tailored to the specific data provided.`;
  }
}
